### ISSUE TITLE
retrieve papers containing words/phrases in their titles/abstracts

### ISSUE THREAD

**Issue by hp0404** [bethgelab/magapi-wrapper#1]
Is it possible to retrieve publications containing words/phrases in their abstracts/titles with the current version of `magapi-wrapper`? 
If not, do you think you're going to include that in the next release? 

As noted in [Paper Entity page](https://docs.microsoft.com/en-us/academic-services/project-academic-knowledge/reference-paper-entity-attributes), API has following attributes:
* 'AW' (Unique, normalized words in abstract, excluding common/stopwords),
* 'W' (Unique, normalized words in title), 
* and 'Ti' (Normalized title) 
 
so I assume it is indeed possible, right?

**Comment by kantharajucn** [comment]
Hi @hp0404 
Firstly sorry for my late response. 
The current version of the `magapi-wrapper` doesn't suüüort retrieval of the abstract. Yes, it is possible to include but MAG announced they are [ending the service by end of 2021](https://www.microsoft.com/en-us/research/project/academic/articles/microsoft-academic-to-expand-horizons-with-community-driven-approach/) so I am not going to include it at this point.

**Comment by hp0404** [comment]
Thanks for the response anyway!
